version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:  
      - DEBUG=1
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes: 
  postgres_data: