# Generated by Django 4.0 on 2022-06-03 09:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkin', models.DateField(verbose_name='checkin')),
                ('checkout', models.DateField(verbose_name='checkout')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='guests.rental', verbose_name='reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
