# Generated by Django 4.0 on 2022-06-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.DateField(verbose_name='checkin'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout',
            field=models.DateField(verbose_name='checkout'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='guests.rental', verbose_name='reservation'),
        ),
    ]
