# Generated by Django 4.0 on 2022-06-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['id'], name='rental_index'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['id'], name='reservation_index'),
        ),
    ]
